### ISSUE TITLE
GetTasks by a special request in the Main Loop! For everyone!

### ISSUE THREAD

**Issue by makushatnik** [AnnoX4uk/Andersen#15]
https://github.com/AnnoX4uk/Andersen/blob/b1469ded81fadb4f24679d34de7a08c1ef066811/tg_bot/tgbot.go#L95

Why not gather that information before? Or is it changes every second or millisecond?

**Comment by AnnoX4uk** [comment]
Because it is simple task. We can gather that with config file, but i'm lazy to rewrite config file after every task is done. 
With this user receives up-to-date information about tasks.
