### ISSUE TITLE
Huge logs when a Github server crashed.

### ISSUE THREAD

**Issue by makushatnik** [AnnoX4uk/Andersen#17]
https://github.com/AnnoX4uk/Andersen/blob/b1469ded81fadb4f24679d34de7a08c1ef066811/tg_bot/tgbot.go#L106

Huge logs when a Github server crashed. If it was 1 mln users in your chatbot.

**Comment by AnnoX4uk** [comment]
This task not suggest 1 mln users, it is simple task for undestanding telegram api and go language.
