### ISSUE TITLE
How chatbot can receive a message?

### ISSUE THREAD

**Issue by makushatnik** [AnnoX4uk/Andersen#18]
https://github.com/AnnoX4uk/Andersen/blob/b1469ded81fadb4f24679d34de7a08c1ef066811/tg_bot/tgbot.go#L86

What if user typed a "legal" for your chatbot message, like: **/git** or: **/GIT**? Will it work?

**Comment by AnnoX4uk** [comment]
Yes. It is basic functional of telegram api. If you add "command" to your bot with @botfather, command will bee caseinsensetive.
