### ISSUE TITLE
Why not prepare a service file before deploy?

### ISSUE THREAD

**Issue by makushatnik** [AnnoX4uk/Andersen#2]
https://github.com/AnnoX4uk/Andersen/blob/b1469ded81fadb4f24679d34de7a08c1ef066811/ansible_assigment/playbook.yml#L115

I think, you can create a service file and just copy it on the deploy time.
It'll make your playbook smaller.

**Comment by AnnoX4uk** [comment]
Yes, but you need prepare a file. In this way you not need any files, exclude playbook.
