### ISSUE TITLE
Is that all the Nginx config?

### ISSUE THREAD

**Issue by makushatnik** [AnnoX4uk/Andersen#5]
https://github.com/AnnoX4uk/Andersen/blob/b1469ded81fadb4f24679d34de7a08c1ef066811/ansible_assigment/playbook.yml#L76

Is that all the Nginx config?

**Comment by AnnoX4uk** [comment]
Nope. It create config file with next content:
server {
            listen 80 default_server;
            location / {
              proxy_pass http://127.0.0.1:8080;
             }
          }
