### ISSUE TITLE
3 times you're getting data within double dot.

### ISSUE THREAD

**Issue by makushatnik** [AnnoX4uk/Andersen#7]
https://github.com/AnnoX4uk/Andersen/blob/b1469ded81fadb4f24679d34de7a08c1ef066811/ansible_assigment/zoo_app/interface.py#L64

3 times you're getting data within double dot.
It's expensive operations.

**Comment by AnnoX4uk** [comment]
Do you have proof about it ?

Anyway, this app is just for study, it is not high load application.
